//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Installer.rc
//
#define IDD_INSTALLER_DIALOG            102
#define IDM_ABOUT                       103
#define IDM_EXIT                        105
#define IDI_INSTALLER                   107
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_WELCOME              129
#define IDD_DIALOG_LICENSE              130
#define IDD_DIALOG_SERIAL               131
#define IDD_DIALOG_MESSAGE_BOX_OK       132
#define IDD_DIALOG_WHAT_TO_INSTALL      133
#define IDD_DIALOG_MESSAGE_BOX_YES_NO   134
#define IDD_DIALOG_DIRECTORY            135
#define IDD_DIALOG_FOLDER               136
#define IDD_DIALOG_REVIEW               137
#define IDD_DIALOG_WOL1                 138
#define IDD_DIALOG_FINAL                139
#define IDD_DIALOG_TRANSITION           140
#define IDD_DIALOG_COPY                 141
#define IDD_DIALOG_BROWSER              143
#define IDD_DIALOG_WOL2                 144
#define IDD_DIALOG_CARD_SELECTION       145
#define IDD_DIALOG_MESSAGE_BOX_RETRY_QUIT 149
#define IDS_INSTALL_CD_VOLUME_NAME      163
#define IDS_GAME_PRODUCT_KEY            164
#define IDS_WOLAPI_SKU                  183
#define IDS_WOLREGISTER_SKU             184
#define IDS_GAME_EXECUTABLE_FILENAME    185
#define IDS_README_FILENAME             190
#define IDS_WORD_README_FILENAME        190
#define IDS_README_ICON_FILENAME        191
#define IDS_GAME_UNINSTALL_FILENAME     194
#define IDS_INTERNET_REGISTRATION_FILENAME 196
#define IDS_WOL_UNINSTALL_FILENAME      198
#define IDS_WWCONFIG_FILENAME           224
#define IDS_APPLICATION_MAIN_WINDOW     225
#define IDS_AUTORUN_MAIN_WINDOW         226
#define IDS_RESOURCE_APPLICATION_ERROR  227
#define IDS_GAME_INI_FILENAME           240
#define IDS_SETUP_INI_FILENAME          241
#define IDS_WOL_INI_FILENAME            242
#define IDS_WOLAPI_DLL_FILENAME         243
#define IDS_WOLBROWSER_DLL_FILENAME     245
#define IDS_TEXT_README_FILENAME        246
#define IDS_GAME_UNINSTALL_LOG_FILENAME 247
#define IDS_WOL_UNINSTALL_LOG_FILENAME  248
#define IDS_SERIAL_ENCRYPTION_FILENAME  249
#define IDS_GAME_DIRECTORY_NAME         250
#define IDS_WOL_DIRECTORY_NAME          251
#define IDS_NON_DISCLOSURE_AGREEMENT    252
#define IDS_AGREE_TO_NDA                253
#define IDS_RESOURCE_DEFAULT_GAME_PATH  254
#define IDS_RESOURCE_DEFAULT_WOL_PATH   255
#define IDS_RESOURCE_DEFAULT_GAME_FOLDER 256
#define IDS_RESOURCE_DEFAULT_WOL_FOLDER 257
#define IDS_RESOURCE_GAME_PRODUCT_NAME  258
#define IDS_RESOURCE_WOL_PRODUCT_NAME   259
#define IDS_RESOURCE_WOLREGISTER_NAME   260
#define IDS_RESOURCE_WOLBROWSER_NAME    261
#define IDS_RESOURCE_AUTO_UPDATE_TITLE  262
#define IDS_RESOURCE_README_TITLE       263
#define IDS_RESOURCE_GAME_UNINSTALL_TITLE 264
#define IDS_RESOURCE_INTERNET_REGISTRATION_TITLE 265
#define IDS_RESOURCE_WWCONFIG_TITLE     266
#define IDS_RESOURCE_WOL_UNINSTALL_TITLE 267
#define IDS_RESOURCE_VERBOSE_GAME_PRODUCT_NAME 268
#define IDS_RESOURCE_PLAY_ONLINE_WITH_GAMESPY 269
#define IDC_WELCOME_STATIC2             1001
#define IDC_WELCOME_STATIC1             1005
#define IDC_WELCOME_FRAME               1007
#define IDC_LICENSE_CHECK               1008
#define IDC_LICENSE_STATIC2             1009
#define IDC_LICENSE_QUERY               1009
#define IDC_LICENSE_STATIC1             1011
#define IDC_LICENSE_HEADING             1011
#define IDC_BUTTON_BACK                 1013
#define IDC_SERIAL_EDIT1                1014
#define IDC_SERIAL_EDIT2                1016
#define IDC_SERIAL_EDIT3                1017
#define IDC_SERIAL_EDIT4                1018
#define IDC_AGREEMENT_STATIC_AGREE      1021
#define IDC_AGREEMENT_STATIC_DISAGREE   1022
#define IDC_MESSAGE_BOX_STATIC          1023
#define IDC_SERIAL_STATIC               1024
#define IDC_WHAT_TO_INSTALL_STATIC      1026
#define IDC_WHAT_TO_INSTALL_CHECK1      1027
#define IDC_WHAT_TO_INSTALL_CHECK2      1028
#define IDC_WHAT_TO_INSTALL_CHECK3      1029
#define IDC_BUTTON_BROWSE               1035
#define IDC_DIRECTORY_STATIC1           1037
#define IDC_DIRECTORY_STATIC2           1039
#define IDC_DIRECTORY_STATIC3           1040
#define IDC_DIRECTORY_EDIT              1041
#define IDC_FOLDER_EDIT                 1045
#define IDC_FOLDER_STATIC1              1046
#define IDC_FOLDER_STATIC2              1047
#define IDC_FOLDER_STATIC3              1048
#define IDC_FOLDER_LIST                 1049
#define IDC_REVIEW_STATIC1              1051
#define IDC_REVIEW_STATIC2              1053
#define IDC_WOL1_STATIC                 1054
#define IDC_FINAL_STATIC1               1055
#define IDC_FINAL_STATIC2               1056
#define IDC_FINAL_CHECK1                1057
#define IDC_FINAL_CHECK2                1058
#define IDC_FINAL_CHECK3                1059
#define IDC_FINAL_STATIC3               1060
#define IDC_BUTTON_YES                  1061
#define IDC_BUTTON_NO                   1062
#define IDC_TRANSITION_STATIC1          1070
#define IDC_EVA_UPDATING1               1070
#define IDC_TRANSITION_STATIC2          1071
#define IDC_EVA_UPDATING2               1071
#define IDC_TRANSITION_STATIC3          1072
#define IDC_PLEASE_STANDBY              1072
#define IDC_COPY_VIEWER                 1073
#define IDC_COPY_DESCRIPTION            1074
#define IDC_COPY_STATUS                 1075
#define IDC_COPY_STATUS1                1075
#define IDC_LICENSE_EDIT                1076
#define IDC_COPY_PERCENTAGE             1077
#define IDC_BROWSER_TREE                1078
#define IDC_BROWSER_STATIC              1079
#define IDC_COPY_HEADER                 1080
#define IDC_REVIEW_EDIT                 1081
#define IDC_WOL2_LIST                   1084
#define IDC_WOL2_EDIT                   1085
#define IDC_WOL2_STATIC1                1086
#define IDC_WOL2_STATIC2                1087
#define IDC_CARD_SELECTION_LIST         1088
#define IDC_WHAT_TO_INSTALL_CHECK4      1090
#define IDC_WELCOME_EDIT                1092
#define IDC_COPY_STATUS2                1093
#define IDC_BUTTON_RETRY                1094
#define IDC_BUTTON_QUIT                 1095
#define IDC_START_POSITION              1096
#define IDC_BIO_MONITOR_AND_LOCAL_RADAR_ACTIVATING 1097
#define IDC_BIO_MONITOR_ACTIVATING      1097
#define IDC_INITIALIZING_OBJECTIVES_SYSTEM 1098
#define IDC_UPDATING_WEAPON_STATUS      1099
#define IDC_TARGETING_SYSTEM_ONLINE     1100
#define IDC_SCANNING_LOCAL_RADAR        1102
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
