/*
**	Command & Conquer Renegade(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class RenegadeNet */

#ifndef _Included_RenegadeNet
#define _Included_RenegadeNet
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: stopThreadPermission */
#undef RenegadeNet_MIN_PRIORITY
#define RenegadeNet_MIN_PRIORITY 1L
#undef RenegadeNet_NORM_PRIORITY
#define RenegadeNet_NORM_PRIORITY 5L
#undef RenegadeNet_MAX_PRIORITY
#define RenegadeNet_MAX_PRIORITY 10L
/*
 * Class:     RenegadeNet
 * Method:    startWinSock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RenegadeNet_startWinSock
  (JNIEnv *, jclass);

/*
 * Class:     RenegadeNet
 * Method:    stopWinSock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RenegadeNet_stopWinSock
  (JNIEnv *, jclass);

/*
 * Class:     RenegadeNet
 * Method:    _nativeSendGR
 * Signature: ([Ljava/lang/String;[D)I
 */
JNIEXPORT jint JNICALL Java_RenegadeNet__1nativeSendGR
  (JNIEnv *, jclass, jobjectArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
