set(NVDXTLIB_ROOT_DIR "${PROJECT_SOURCE_DIR}/Code/third_party/nvDXTLib")

find_path(NVDXTLIB_INCLUDE_DIRS nvdxtlib.h PATHS
        "${NVDXTLIB_ROOT_DIR}/inc"
)

find_library(NVDXTLIB_LIBRARY nvDXTlib "${NVDXTLIB_ROOT_DIR}/lib" NO_DEFAULT_PATH)
set(NVDXTLIB_LIBRARIES ${NVDXTLIB_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(NVDXTLIB DEFAULT_MSG NVDXTLIB_ROOT_DIR NVDXTLIB_LIBRARIES NVDXTLIB_INCLUDE_DIRS)
mark_as_advanced(NVDXTLIB_INCLUDE_DIRS NVDXTLIB_LIBRARY)